In [97]:
import numpy as np
import time

n = 1_000_000

python_list = list(range(n))
numpy_array = np.arange(n)

start_time = time.time()
squared_list = [x**2 for x in range(n)]
list_time = time.time() - start_time

start_time = time.time()
squared_array = numpy_array**2
numpy_time = time.time() - start_time
difference = abs(list_time - numpy_time)
print("-" * 60)


print(f"{list_time:.4f} Seconds for squared_list.")
print(f"{numpy_time:.4f} Seconds for NumPy.")

if (numpy_time > list_time):
    print(f"squared_list was faster?!; by {difference:.4f} seconds")
else:
    print(f"NumPy was faster by {difference:.4f} seconds.")

print("-" * 60)





------------------------------------------------------------
0.2485 Seconds for squared_list.
0.0109 Seconds for NumPy.
NumPy was faster by 0.2375 seconds.
------------------------------------------------------------


In [96]:
import numpy as np

matrix = np.random.rand(4, 4)
matrix = np.round(matrix, 2)
print("-" * 60)
print("Matrix:")
print(matrix)

print("-" * 60)
print (f"{matrix.shape} Shape")
print (f"{matrix.size} is the size of the matrix.")
print (f"{matrix.ndim} Dimensions")

------------------------------------------------------------
Matrix:
[[0.65 0.05 0.18 0.88]
 [0.47 0.57 0.79 0.77]
 [0.96 0.18 0.33 0.53]
 [0.76 0.01 0.58 0.48]]
------------------------------------------------------------
(4, 4) Shape
16 is the size of the matrix.
2 Dimensions


In [98]:
import numpy as np

matrix = np.eye(3, 3)
array = np.random.randint(1, 101, size = 20)
print("-" * 60)
print("3x3 Identity Matrix:")
print(matrix)
print("-" * 60)
print(array)

------------------------------------------------------------
3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
------------------------------------------------------------
[89 57 18  5  2 94 72 11 90 34 95 28 82 36 46  9 13 96 60  9]


In [124]:
matrix = np.random.randint(1,11, size = (5, 5))
matrix = matrix.round(1)
print(matrix)
print("-" * 60)

print("Third row from above matrix:")
third_row = matrix[2, :]
print(third_row)
print("-" * 60)

print("Last two columns:")
last_columns = matrix[:, -2:]
print(last_columns)
print("-" * 60)

print("3x3 Submatrix from the center:")
submatrix = matrix[1:4, 1:4]
print(submatrix)

[[10  2  4  7  2]
 [ 4  3  7  4  9]
 [10  2  8  1  6]
 [ 8  7  7  5  1]
 [ 7  5 10  4  6]]
------------------------------------------------------------
Third row from above matrix:
[10  2  8  1  6]
------------------------------------------------------------
Last two columns:
[[7 2]
 [4 9]
 [1 6]
 [5 1]
 [4 6]]
------------------------------------------------------------
3x3 Submatrix from the center:
[[3 7 4]
 [2 8 1]
 [7 7 5]]


In [136]:
import numpy as np

array = np.random.randint(1, 20, size = (20))
print("1D array of 20 elements:")
print(array)
print("-" * 60)

matrix = array.reshape(4,5)
print("Reshaping...")
print("-" * 60)

print("4x5 Matrix:")
print(matrix)

1D array of 20 elements:
[18 15  9  9  3  9 11  8 11 16 14  2 13 15  8 11 16  9  1  8]
------------------------------------------------------------
Reshaping...
------------------------------------------------------------
4x5 Matrix:
[[18 15  9  9  3]
 [ 9 11  8 11 16]
 [14  2 13 15  8]
 [11 16  9  1  8]]
